export const OTHER_CITY_VALUE = "OTHER";
export const CUSTOM_CITY_MAX_LENGTH = 80;

export const nigeriaLocations = {
  Abia: ["Aba", "Umuahia"],
  Adamawa: ["Jimeta", "Mubi", "Yola"],
  "Akwa Ibom": ["Eket", "Ikot Ekpene", "Uyo"],
  Anambra: ["Awka", "Nnewi", "Onitsha"],
  Bauchi: ["Azare", "Bauchi", "Jama'are"],
  Bayelsa: ["Brass", "Ogbia", "Yenagoa"],
  Benue: ["Gboko", "Makurdi", "Otukpo"],
  Borno: ["Bama", "Biu", "Maiduguri"],
  "Cross River": ["Calabar", "Ikom", "Ogoja"],
  Delta: ["Asaba", "Sapele", "Ughelli", "Warri"],
  Ebonyi: ["Abakaliki", "Afikpo"],
  Edo: ["Benin City", "Ekpoma", "Uromi"],
  Ekiti: ["Ado-Ekiti", "Ikere-Ekiti"],
  Enugu: ["Enugu", "Nsukka", "Oji River"],
  FCT: ["Abuja", "Gwagwalada", "Kubwa"],
  Gombe: ["Billiri", "Gombe", "Kaltungo"],
  Imo: ["Oguta", "Orlu", "Owerri"],
  Jigawa: ["Dutse", "Gumel", "Hadejia"],
  Kaduna: ["Kaduna", "Kafanchan", "Zaria"],
  Kano: ["Kano", "Rano", "Wudil"],
  Katsina: ["Daura", "Funtua", "Katsina"],
  Kebbi: ["Argungu", "Birnin Kebbi", "Yauri"],
  Kogi: ["Idah", "Kabba", "Lokoja"],
  Kwara: ["Ilorin", "Offa", "Pategi"],
  Lagos: ["Badagry", "Epe", "Ikeja", "Ikorodu", "Lekki", "Surulere"],
  Nasarawa: ["Karu", "Keffi", "Lafia"],
  Niger: ["Bida", "Kontagora", "Minna", "Suleja"],
  Ogun: ["Abeokuta", "Ijebu Ode", "Ota", "Sagamu"],
  Ondo: ["Akure", "Ikare", "Ondo"],
  Osun: ["Ede", "Ife", "Ilesa", "Osogbo"],
  Oyo: ["Ibadan", "Ogbomoso", "Oyo"],
  Plateau: ["Bukuru", "Jos", "Pankshin"],
  Rivers: ["Bonny", "Obio-Akpor", "Port Harcourt"],
  Sokoto: ["Sokoto", "Tambuwal", "Wamakko"],
  Taraba: ["Bali", "Jalingo", "Wukari"],
  Yobe: ["Damaturu", "Gashua", "Potiskum"],
  Zamfara: ["Gusau", "Kaura Namoda", "Talata Mafara"],
} as const satisfies Record<string, readonly string[]>;

export const nigeriaStates = Object.keys(nigeriaLocations) as Array<keyof typeof nigeriaLocations>;
