"use client";

import Image from "next/image";
import Link from "next/link";
import { Minus, Plus, ShoppingBag } from "lucide-react";
import { useEffect, useRef } from "react";

import { Dialog, DialogClose, DialogCloseButton, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { formatNairaFromMinor } from "@/features/catalogue/fields";
import { ProductBottlePlaceholder } from "@/features/catalogue/PublicProductCards";
import { siteConfig } from "@/config/site";
import { useCart } from "./CartProvider";

function issueText(issue?: string, stock?: number) { return issue === "missing" ? "This perfume is no longer available." : issue === "unavailable" ? "This size is currently out of stock." : `Only ${stock ?? 0} available — reduce the quantity.`; }

function QuantityStepper({ line }: { line: ReturnType<typeof useCart>["lines"][number] }) {
  const { changeQuantity } = useCart();
  const maximum = line.stock ?? 0;
  return <div className="flex h-10 items-center border"><button type="button" className="grid size-10 place-items-center disabled:opacity-40" onClick={() => changeQuantity(line.perfumeVariantId, line.requestedQuantity - 1)} disabled={line.requestedQuantity <= 1} aria-label={`Decrease quantity for ${line.name ?? "unavailable item"}`}><Minus className="size-4" /></button><output className="grid w-9 place-items-center text-sm" aria-live="polite">{line.requestedQuantity}</output><button type="button" className="grid size-10 place-items-center disabled:opacity-40" onClick={() => changeQuantity(line.perfumeVariantId, line.requestedQuantity + 1)} disabled={!line.isValid || line.requestedQuantity >= maximum} aria-label={`Increase quantity for ${line.name ?? "unavailable item"}`}><Plus className="size-4" /></button></div>;
}

export function CartLine({ line }: { line: ReturnType<typeof useCart>["lines"][number] }) {
  const { removeItem, changeQuantity } = useCart();
  const name = line.name ?? "Unavailable perfume";
  return <article className="flex gap-4 border-b py-5"><div className="relative h-28 w-22 shrink-0 overflow-hidden bg-jp-stone">{line.imageUrl ? <Image src={line.imageUrl} alt={line.imageAlt || ""} fill unoptimized sizes="88px" className="object-contain" /> : <ProductBottlePlaceholder />}</div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><h2 className="font-display text-3xl leading-none">{name}</h2>{line.sizeLabel ? <p className="mt-2 text-sm text-jp-text-secondary">{line.sizeLabel}</p> : null}</div>{line.unitPriceMinor !== undefined ? <p className="shrink-0 text-sm font-semibold">{formatNairaFromMinor(line.unitPriceMinor)}</p> : null}</div>{line.isValid ? <div className="mt-4 flex items-center justify-between gap-3"><QuantityStepper line={line} /><p className="text-sm font-medium">{formatNairaFromMinor(line.lineAmountMinor)}</p></div> : <div className="mt-4"><p className="text-sm text-destructive" role="alert">{issueText(line.issue, line.stock)}</p>{line.issue === "over-quantity" && line.stock ? <button type="button" className="mt-2 text-sm underline" onClick={() => changeQuantity(line.perfumeVariantId, line.stock ?? 1)}>Set quantity to {line.stock}</button> : null}</div>}<button type="button" className="mt-3 text-[11px] uppercase tracking-[.12em] text-jp-text-secondary underline" onClick={() => removeItem(line.perfumeVariantId)} aria-label={`Remove ${name} from cart`}>Remove</button></div></article>;
}

function Summary({ preview = false }: { preview?: boolean }) {
  const { count, subtotalMinor, hasInvalidLines, resolutionState } = useCart();
  const blockedMessage = resolutionState === "resolving" ? "Checking current availability…" : resolutionState === "error" ? "Cart availability could not be checked. Try again before Checkout." : hasInvalidLines ? "Resolve unavailable items before Checkout." : undefined;
  if (preview) return <section className="border-t pt-4" aria-label="Cart subtotal"><div className="flex items-baseline justify-between"><span className="text-sm font-semibold">Subtotal</span><strong className="font-display text-3xl">{formatNairaFromMinor(subtotalMinor)}</strong></div>{blockedMessage ? <p className="mt-2 text-sm text-destructive" role="alert">{blockedMessage}</p> : null}<Link href={siteConfig.routes.checkout} aria-disabled={hasInvalidLines} onClick={(event) => { if (hasInvalidLines) event.preventDefault(); }} className={`mt-4 flex h-12 items-center justify-center bg-jp-text-primary text-sm font-semibold uppercase tracking-[.08em] text-jp-surface ${hasInvalidLines ? "pointer-events-none opacity-45" : ""}`}>Checkout</Link></section>;
  return <section className="border bg-jp-surface p-6 lg:sticky lg:top-6" aria-label="Order summary"><p className="text-xs font-semibold uppercase tracking-[.15em] text-jp-olive">Order summary</p><div className="mt-6 flex justify-between text-sm"><span>Items</span><span>{count}</span></div><div className="mt-3 flex items-baseline justify-between"><span>Subtotal</span><strong className="font-display text-3xl">{formatNairaFromMinor(subtotalMinor)}</strong></div><p className="mt-5 text-xs leading-5 text-jp-text-secondary">Availability is checked again when you place your order. Payment is not taken online.</p>{blockedMessage ? <p className="mt-3 text-sm text-destructive" role="alert">{blockedMessage}</p> : null}<Link href={siteConfig.routes.checkout} aria-disabled={hasInvalidLines} onClick={(event) => { if (hasInvalidLines) event.preventDefault(); }} className={`mt-6 flex h-13 items-center justify-center bg-jp-text-primary text-sm font-semibold uppercase tracking-[.08em] text-jp-surface ${hasInvalidLines ? "pointer-events-none opacity-45" : ""}`}>Checkout</Link></section>;
}

export function CartPreview() {
  const { isOpen, setOpen, lines, count, resolutionState } = useCart();
  const focusBeforeOpen = useRef<HTMLElement | null>(null);
  const wasOpen = useRef(false);
  useEffect(() => { if (isOpen) focusBeforeOpen.current = document.activeElement instanceof HTMLElement ? document.activeElement : null; if (wasOpen.current && !isOpen) focusBeforeOpen.current?.focus(); wasOpen.current = isOpen; }, [isOpen]);
  return <Dialog open={isOpen} onOpenChange={setOpen}><DialogContent className="inset-y-0 right-0 left-auto flex h-full w-full max-w-[31rem] translate-x-0 translate-y-0 flex-col overflow-y-auto border-y-0 border-r-0 p-6 sm:p-8 max-lg:inset-x-0 max-lg:top-auto max-lg:h-auto max-lg:max-h-[78vh] max-lg:max-w-none max-lg:rounded-t-sheet"><p className="text-xs font-semibold uppercase tracking-[.15em] text-jp-olive">Added to cart</p><DialogTitle className="mt-2">Your cart</DialogTitle><DialogDescription className="sr-only">Review items in your cart.</DialogDescription><DialogCloseButton />{resolutionState === "resolving" && count ? <p className="mt-6 text-sm text-jp-text-secondary" role="status">Checking your cart…</p> : resolutionState === "error" && count ? <p className="mt-6 text-sm text-destructive" role="alert">We could not check your cart. Checkout is unavailable until it is resolved.</p> : lines.length ? <div className="mt-5">{lines.map((line) => <CartLine key={line.perfumeVariantId} line={line} />)}<Summary preview /><div className="mt-3 grid gap-2 sm:grid-cols-2"><DialogClose asChild><Link href={siteConfig.routes.perfumes} className="flex h-11 items-center justify-center border text-sm font-semibold">Continue Browsing</Link></DialogClose><DialogClose asChild><Link href={siteConfig.routes.cart} className="flex h-11 items-center justify-center border text-sm font-semibold">View Full Cart</Link></DialogClose></div></div> : <p className="mt-6 text-sm text-jp-text-secondary">Your cart is empty.</p>}</DialogContent></Dialog>;
}

export function CartUtility() { const { count, setOpen } = useCart(); const contents = <><ShoppingBag className="size-5" aria-hidden="true" /><span className="grid size-6 place-items-center rounded-full border border-[#beb7aa] text-[11px] font-semibold" aria-live="polite">{count}</span></>; return count ? <button type="button" onClick={() => setOpen(true)} className="inline-flex items-center gap-2" aria-label={`Open cart, ${count} items`}>{contents}</button> : <Link href={siteConfig.routes.cart} className="inline-flex items-center gap-2" aria-label="Open cart, 0 items">{contents}</Link>; }

export function FullCart() { const { lines, count, resolutionState } = useCart(); if (count && resolutionState === "resolving") return <section className="mx-auto max-w-public-container px-public-gutter-mobile py-16 lg:px-public-gutter-desktop"><h1 className="font-display text-6xl">Your cart</h1><p className="mt-5 text-jp-text-secondary" role="status">Checking current availability…</p></section>; if (count && resolutionState === "error") return <section className="mx-auto max-w-public-container px-public-gutter-mobile py-16 lg:px-public-gutter-desktop"><h1 className="font-display text-6xl">Your cart</h1><p className="mt-5 text-destructive" role="alert">We could not check your cart. Please reload before Checkout.</p><Summary /></section>; if (!lines.length && count === 0) return <section className="mx-auto max-w-public-container px-public-gutter-mobile py-16 lg:px-public-gutter-desktop lg:py-24"><div className="border-b pb-7"><p className="text-xs font-semibold uppercase tracking-[.18em] text-jp-text-secondary">Your cart</p><h1 className="mt-3 font-display text-6xl">Nothing here yet.</h1></div><div className="mt-8 flex flex-col justify-between gap-8 bg-jp-stone p-8 lg:flex-row lg:items-center lg:p-14"><div className="max-w-xl"><h2 className="font-display text-5xl">Start with a perfume you’d like to try.</h2><p className="mt-4 text-jp-text-secondary">Browse available perfumes, choose a size, and add it to your cart. You can continue browsing before checkout.</p></div><div className="flex flex-wrap gap-3"><Link href={siteConfig.routes.perfumes} className="bg-jp-text-primary px-6 py-3 text-sm font-semibold text-jp-surface">Browse Perfumes</Link><Link href={siteConfig.routes.helpMeChoose} className="border border-jp-text-primary px-6 py-3 text-sm font-semibold">Find My Scent</Link></div></div></section>;
  return <section className="mx-auto max-w-public-container px-public-gutter-mobile py-12 lg:px-public-gutter-desktop lg:py-16"><div className="flex items-end justify-between border-b pb-6"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-jp-olive">Your cart</p><h1 className="mt-3 font-display text-6xl lg:text-7xl">Review your choices.</h1></div><p className="text-sm text-jp-text-secondary">{count} {count === 1 ? "item" : "items"}</p></div><div className="mt-8 grid gap-10 lg:grid-cols-[1fr_22rem]"><div>{lines.map((line) => <CartLine key={line.perfumeVariantId} line={line} />)}<Link href={siteConfig.routes.perfumes} className="mt-6 inline-block text-sm font-semibold uppercase tracking-[.08em]">← Continue Browsing</Link></div><Summary /></div></section>;
}
