import Link from "next/link";

import { GalleryProductCard } from "@/features/catalogue/PublicProductCards";
import { ScentCharacterBrowse } from "@/features/catalogue/ScentCharacter";
import { getFeaturedPerfumes, publicScentCharacters } from "@/features/catalogue/public-catalogue";
import { siteConfig } from "@/config/site";

export const dynamic = "force-dynamic";

export default async function HomePage() {
  const { hero, products } = await getFeaturedPerfumes();
  return <>
    <section className="mx-auto grid max-w-public-container gap-8 px-public-gutter-mobile py-8 lg:grid-cols-[1.15fr_.85fr] lg:px-public-gutter-desktop lg:py-14">
      <div className="flex flex-col justify-center"><p className="text-sm uppercase tracking-[0.18em] text-jp-text-secondary">A quiet scent gallery</p><h1 className="mt-5 max-w-xl font-display text-6xl leading-[.9] lg:text-8xl">Find a scent that feels like you.</h1><p className="mt-6 max-w-md leading-7 text-jp-text-secondary">A considered collection of fragrances for every mood, moment, and memory.</p><div className="mt-8 flex flex-wrap gap-3"><Link href={siteConfig.routes.perfumes} className="bg-jp-text-primary px-5 py-3 text-sm text-jp-surface">Explore perfumes</Link><Link href={siteConfig.routes.helpMeChoose} className="border px-5 py-3 text-sm">Help me choose</Link></div></div>
      {hero ? <div><GalleryProductCard perfume={hero} /></div> : <div className="grid min-h-96 place-items-center bg-jp-stone p-8 text-center"><div><h2 className="font-display text-5xl">A collection is taking shape.</h2><Link className="mt-6 inline-block border px-5 py-3 text-sm" href={siteConfig.routes.helpMeChoose}>Help me choose</Link></div></div>}
    </section>
    {products.length > 0 && <section className="mx-auto max-w-public-container px-public-gutter-mobile py-16 lg:px-public-gutter-desktop"><div className="flex items-end justify-between gap-4"><div><p className="text-sm uppercase tracking-[0.18em] text-jp-text-secondary">Featured collection</p><h2 className="mt-2 font-display text-5xl">Start somewhere beautiful.</h2></div><Link href={siteConfig.routes.perfumes} className="text-sm underline underline-offset-4">View all</Link></div><div className="mt-8 grid gap-5 lg:grid-cols-3">{products.map((perfume) => <GalleryProductCard key={perfume.id} perfume={perfume} />)}</div></section>}
    <section className="bg-jp-green-surface py-16"><div className="mx-auto max-w-public-container px-public-gutter-mobile lg:px-public-gutter-desktop"><p className="text-sm uppercase tracking-[0.18em] text-jp-text-secondary">Browse by mood</p><h2 className="mt-2 font-display text-5xl">What are you drawn to?</h2><div className="mt-8"><ScentCharacterBrowse values={publicScentCharacters} /></div></div></section>
    <section className="mx-auto grid max-w-public-container gap-8 px-public-gutter-mobile py-16 lg:grid-cols-2 lg:px-public-gutter-desktop"><div><p className="text-sm uppercase tracking-[0.18em] text-jp-text-secondary">A more personal route</p><h2 className="mt-3 font-display text-6xl leading-[.92]">Let your preferences lead.</h2></div><div className="border bg-jp-surface p-8"><p className="text-jp-text-secondary">Not sure where to begin? A few simple choices reveal a thoughtful, availability-aware shortlist.</p><Link href={siteConfig.routes.helpMeChoose} className="mt-7 inline-block bg-jp-text-primary px-5 py-3 text-sm text-jp-surface">Find my scent</Link></div></section>
    <section className="border-y bg-jp-surface py-16"><div className="mx-auto max-w-public-container px-public-gutter-mobile lg:px-public-gutter-desktop"><p className="text-sm uppercase tracking-[0.18em] text-jp-text-secondary">From choosing to confirmation</p><h2 className="mt-2 font-display text-5xl">How ordering works</h2><div className="mt-8 grid gap-6 md:grid-cols-3">{[["01", "Choose", "Find a perfume and size you love."], ["02", "Add", "Add your choices to your bag."], ["03", "Review", "Check your selections before sharing details."], ["04", "Confirm", "Send your order for personal confirmation."], ["05", "Payment", "Receive payment details directly from JPScents."], ["06", "Delivery", "Your order is prepared with care."]].map(([number, title, copy]) => <div key={number} className="border-t pt-4"><span className="text-sm text-jp-olive">{number}</span><h3 className="mt-3 font-display text-3xl">{title}</h3><p className="mt-2 text-sm leading-6 text-jp-text-secondary">{copy}</p></div>)}</div></div></section>
    <section className="mx-auto max-w-public-container px-public-gutter-mobile py-16 lg:px-public-gutter-desktop"><p className="text-sm uppercase tracking-[.18em] text-jp-text-secondary">A little reassurance</p><h2 className="mt-2 font-display text-5xl">A considered beginning.</h2><div className="mt-8 grid gap-0 border-t lg:grid-cols-2">{[["Thoughtful guidance", "Use our scent finder when you want a considered starting point."], ["Available selections", "We only recommend perfumes currently available to choose."], ["Personal confirmation", "Each order is confirmed directly with care."], ["Questions before choosing", "Our team is happy to help you find a scent that feels right."]].map(([question, answer]) => <details key={question} className="border-b p-5"><summary className="cursor-pointer font-medium">{question}</summary><p className="mt-3 text-sm text-jp-text-secondary">{answer}</p></details>)}</div><div className="mt-12 border bg-jp-green-surface p-8 text-center"><h2 className="font-display text-5xl">Ready to find your scent?</h2><Link href={siteConfig.routes.helpMeChoose} className="mt-6 inline-block bg-jp-text-primary px-5 py-3 text-sm text-jp-surface">Find my scent</Link></div></section>
  </>;
}
